#!/bin/bash

if [ "$CC" == "clang" ]; then
    echo Warning:
    echo Valgrind does not read properly DWARF5 as generated by Clang14
    echo Consider using GCC instead
fi

cmake -S . -B debug -DTARGET=Debug
cmake --build debug
if [ $? -eq 0 ]; then
    valgrind --leak-check=yes debug/cpuUsage
else
    echo BUILDING COMMAND FAILED
fi
